name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Common versions
  GO_VERSION: '1.22.x'
  GOLANGCI_VERSION: 'v1.54.2'

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  vulnerability-scan-fs:
    name: vulnerability scan
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: unit-tests
        shell: bash
        run: ls -la

      - name: run trivy vulnerability scanner in fs mode
        # https://github.com/aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          scan-ref: '.'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
